### ISSUE TITLE
As a user, I want to easily read and use the main site navigation so I can get to the content that interests me.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#110]
## testing notes
zeplin links: [L](https://zpl.io/aMvvknK) / [L expanded](https://zpl.io/bJvvkgW)

- the nav should expand to show "cards" with second and third-level items when you hover over a top-level item
- top-level items should have a larger font size for increased readability
- on a large screen, second-level items should stack horizontally
- on a medium screen/tablet, second-level items should stack vertically
- third-level items should be underneath their second-level parent
- when you scroll down quickly, the popup "cards" should hide themselves along with the nav
- popup behavior should be "generous": the "cards" should stay open as long as you want them to, but get out of your way when you expect them to

## Notes for development
- larger font size
- make hover nav easier to use

**Comment by jimccasey1** [comment]
I played around with the navigation menus on the test site. all looks good, except a couple of qualifications that i moved into a list at the bottom. 

- (yes) the nav should expand to show "cards" with second and third-level items when you hover over a top-level item
- (yes) top-level items should have a larger font size for increased readability
- (yes) third-level items should be underneath their second-level parent
- (yes) when you scroll down quickly, the popup "cards" should hide themselves along with the nav
- (yes) popup behavior should be "generous": the "cards" should stay open as long as you want them to, but get out of your way when you expect them to

Unsure about these: 
- on a large screen, second-level items should stack horizontally 
--> under 'Resources' it looks like the last item 'Course Offerings' wraps around and is a little awkwardly set against the others? otherwise the horizontal stack works on all the second-level items. 
- on a medium screen/tablet, second-level items should stack vertically
--> yes, but I don't have an iPad for testing, so just used Chrome inspector set to screen size of 768x1024.

**Comment by jimccasey1** [comment]
Updated previous comment. All looks good, so closing now.
