### ISSUE TITLE
As a user, I want to see current, staff, and past projects so I can easily see which projects are active and know more about staff research.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#113]
## Notes for testing
- Go to the main project list page on the test site. You should see sponsored projects broken into sections for current and past projects based on grant dates. 
- Using the drop-down navigation on the right, you should be able to switch to view staff & postdoctoral fellow projects.  These are identified based on the Grant types "Staff R&D" and "Postdoctoral Fellow Research Project"
- In the admin, try adding a new staff or postdoc project or changing existing project dates to check that projects are showing up where they should.
- Ignore how these pages show up in the top-level navigation, that will be handled separately.

## Notes for development
- existing project page becomes current; filter based on grant term, sort by grant date
- include all current sponsored projects + dataset curation projects
- new page for staff and post-doc projects
  - TBD how to flag this in the db? will eventually need current/past sections, how to determine dates?

**Comment by norabenedict** [comment]
The categories (current vs. past) are showing up, and the filtering between "projects" and "staff and postdoctoral research fellow projects" is working fine. However, there seems to be a timeline or date glitch with the "Staff and Postdoctoral Research Fellow Projects" page. My own project appears under "past projects". I played around in the admin with the dates to see if it was entered incorrectly (but it wasn't), and I also tried to move the date around to a more recent date to see if I could get it into the "current projects" section and it wouldn't move. 

To be frank, I find these divisions a little odd and somewhat hierarchical (i.e. the fact that "projects" as a general category is different than what staff/postdocs do here is strange and uninviting). This is especially apparent since grad fellow projects are on the main page, but all staff and postdoc projects are not. Perhaps these waterfall-esque divisions could simply be "Faculty," "Staff," "Postdocs" and then the drop-down navigation would allow for toggling between current and past projects?

**Comment by rlskoeser** [comment]
I think the past/current logic is working correctly; please test again. Possibly requires a hard refresh to pick up changes due to browser caching?

**Comment by norabenedict** [comment]
The navigation on the page seems to work just fine, although I still have a question about the filtering. Do ALL projects, regardless of the type of grant that funds/funded them appear on the first page in "past projects" (as a catch-all) once they are over, or should projects be filtered into a present/past on their respective pages? If the former is true, there is no issue. If the latter is true, there is an issue since Claude's project appears on the regular project page under "past projects."

When I tried to add sample projects to make sure they were displaying correctly through the admin, I was unable to do so. I kept getting error message about the start date I was selecting for my fake projects. I was unable to chose today's date, or any past date as the start time.

**Comment by rlskoeser** [comment]
@norabenedict good catch! Claude's project should be in the past section on the staff & postdoc page, I bet it is in the db wrong. Please try changing it from sponsored project to postdoc research project. 

I'm concerned about the date errors - please check if it's still happening or if it's fixed now (we did have some javascript errors on the admin yesterday that could have impacted that).

**Comment by norabenedict** [comment]
Everything works well now! No date issues and I was able to move projects around from past to present with no issue (on both pages). I changed Claude's project from sponsored project to postdoc research project, and it displays in the correct place now.
