### ISSUE TITLE
As an admin, I want to create and edit staff profiles so I can publish information about staff research and roles.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#13]
## Notes for testing
- edit under profiles -> people
- the profile section defaults to collapsed but I haven't been able to figure out an easy way to change that, so we'll just have to live with that for now
- update 9/20 added username to edit form, should fix the problem encountered before
---

Detailed items that this should include are:

- [x] large photo for detail page
- [x] thumbnail photo for listing
- [x] job title
- [x] education section
- [x] contact info
- [x] paragraph text

**Comment by rlskoeser** [comment]
@bwhicks is your question about who should be able to edit profiles?  Support for non-admin users editing their own profiles is a good idea, but I don't think we should worry about it for the first release.

**Comment by bwhicks** [comment]
@rlskoeser That's it precisely. Thanks for clarifying.

**Comment by mnaydan** [comment]
Am able to edit profiles; all detailed fields listed appear.

Two small admin problems re: creating a staff profile. (1) I can't edit a Person who doesn't have a username associated with them. I'd have to delete the whole entry and readd them to everything they're currently associated with. This is problematic because this is causing 2 faculty directors to appear on the staff page and I can't delete the one Miranda is mistakenly associated with.

<img width="808" alt="screen shot 2017-09-19 at 2 30 21 pm" src="https://user-images.githubusercontent.com/22945600/30609022-2e316bac-9d48-11e7-991e-d402c31b5c1e.png">

(2) I can't add a new Person (staff member) if they are not already a user. It creates this error:
<img width="1267" alt="screen shot 2017-09-19 at 3 02 36 pm" src="https://user-images.githubusercontent.com/22945600/30610275-aab70562-9d4b-11e7-9a6c-88cfefe6a72a.png">

**Comment by rgmunson** [comment]
The fix of including the username by default seems to have fixed both problems. I was able to edit a staff profile without issue and to add a new person who did not already have a username. (I then deleted this fictional person so as not to cause clutter.)
