### ISSUE TITLE
Image skewed on mobile

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#155]
Image getting skewed on mobile - view [live version](https://cdh.princeton.edu/updates/2019/05/16/life-b-floor-my-uaf-experience/)

![Screenshot_2019-05-23-22-20-29](https://user-images.githubusercontent.com/691231/58331661-9cad8880-7e07-11e9-8461-02fc2412dc27.png)

I haven't noticed this before, maybe it is specific to landscape images?

**Comment by thatbudakguy** [comment]
this was caused by a `style=` attribute on the `<img>` tag for the photo that contained width and height css, causing it to scale incorrectly. not sure how this could have happened, since we don't allow the user to specify these attributes by default - maybe if the image was pasted from another document?

i've removed the attributes and checked that it scales correctly. images in other blog posts appear to be unaffected.
