### ISSUE TITLE
As a user, I want to navigate using the header or footer menus, so that I can find the content I'm looking for.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#16]
## Notes for testing
Updated 9/21.  Menu is dynamic but styles are keyed to the content we currently expect (so it could be possible to break things if we're not careful).  
- Contact & Directions is no longer hard-coded in the footer and can be set via menu controls in admin; I think the Subscribe page is going away or just becoming a link, but either way should be handled in admin.
- Social links in the footer have been added.

**Comment by mnaydan** [comment]
Header menu and main footer menu work. Contact and Directions, FAQs and Subscribe buttons appear broken--they redirect to the top of the current page, and I can't find a way to edit these in Mezzanine.

**Comment by rlskoeser** [comment]
@mnaydan good observation.  The links that don't work were hard-coded in the old site and I think I left them here because I wasn't sure how we wanted to handle them.  I think FAQ is going away (because we don't actually have content for it yet) and subscribe will be changing with the change in how we're handling our mailing list.  My inclination is to make it so all of these can be edited and managed in the admin, there's just an open question with how to differentiate header and footer links.

This relates to #6 which I haven't marked as ready for testing yet because of these questions.  But perhaps this story isn't really ready to be tested until that one is complete?

**Comment by rgmunson** [comment]
The navigation from the header all works perfectly. In the footer, the navigation works on the main footer menu (for all the pages on the left side). The links to social media, however, still redirect to the top of the page as when Mary tested. (And, as when Mary tested, I can't seem to change that in Mezzanine.) Not sure if it's a mistake but there are no buttons for "subscribe" or "contact and directions."

**Comment by rlskoeser** [comment]
Subscribe and Contact and Directions were hard-coded previously but I think they should be admin-managed like everything else.  Maybe we can test once I implement the content page import.

I'll add in the social media links.

**Comment by jabauer** [comment]
Social media links work.

Contact page is managed in Admin.
