### ISSUE TITLE
support customized project page staff lists

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#164]
we're seeing this issue currently on PPA because the logic for calculating the project team to display on a project page defaults to the current grant. for PPA, this is a dataset curation grant rather than the main sponsored project grant, so it isn't showing the main project team from the earlier sponsored project grant.

the easiest way to resolve this is to add a flag on memberships that can be set to:
- force alum
- force current
- use grant dates (default - will be current if on latest grant)

**Comment by rlskoeser** [comment]
Checked that project page members displayed correctly first before making any changes. I did notice one problem with people showing up as both current members and alumni. Check bitKlavier and Winthrop. It doesn't look like a data issue, and it's only happening with CDH staff who no longer work here - I'm not sure how that could be coming into play, but seems suspicious.


Tested with PPA, setting members of the sponsored project team as current - showed as expected. 
Tested with S&co, setting members of the current grant as alum - showed as expected.

Was nice to be able to edit on the list view. It's a little confusing since you have to know which grant to edit, but fine for now.

**Comment by rlskoeser** [comment]
I looked again and I think the weird behavior I saw *must* have been caused by a data issue (although I'm not certain what or how, in the case of Xinyi showing as both current and alum on bitKlavier). I can't reproduce it in my dev environment, and I can't see anything in the code that would cause it. I refreshed the test site with current production data and everything displays as I expect. And when I added some overrides, those work as expected.
