### ISSUE TITLE
make main nav fully keyboard-accessible

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#165]
current there's no way to access second-level nav menu items using a keyboard.

we should follow [the W3C nav menu example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html) for how to use this thing with a keyboard (behavior of tab, arrow keys, etc).

**Comment by rlskoeser** [comment]
This looks great, is working properly everywhere I tried it. Tested on Chrome on the home page and on a few secondary pages; tested on the home page in Firefox, Safari, and Opera.

I noticed the active item selection isn't very visible in Firefox, but I guess that's because we're currently using browser defaults.  (Is that on our list of things to think about in future?)

In Chrome I also checked at different simulated screen sizes - in mobile, tabbing skips nav entirely as I would expect it to since the top nav is hidden. It works fine on tablet, although the arrows aren't quite as intuitive since the secondary menus stack vertically.  I don't think that's a problem since you're following an established pattern.
