### ISSUE TITLE
As a content editor, I want to create, edit, and delete content pages in wagtail so that I can manage new and existing site content.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#180]
# testing notes
**fyi** - for the duration of this big upgrade (v3.0), you'll be able to access the _new_ versions of pages at a special URL, `/pages`. so if you were testing the event co-sponsorship form page, you would go to [/pages/events/cosponsor](https://cdh-test-web.princeton.edu/pages/events/cosponsor/).

you should be able to do a direct comparison by looking at the real site (cdh.princeton.edu) and simply removing the "pages" part of the URL, like [/events/cosponsor](https://cdh-test-web.princeton.edu/pages/events/cosponsor/). and ideally, nothing should appear different at all - we want all the pages to look the same as they did before.

**be careful** because a lot of links (especially in the navigation menus) will still take you to the old versions of pages. if you're testing a page, double-check that the URL has `/pages` in it, because you want to be looking at the new versions.

the big changes will be on the admin side. instead of going to [/admin](https://cdh-test-web.princeton.edu/admin/), you'll now be visiting [/cms](https://cdh-test-web.princeton.edu/cms/). the purpose is the same, but the interface is very different! we're hoping that it will improve lots of workflows for adding and updating content. if there are things you don't like, we might be able to customize them later.

for testing this issue, we want to be able to create new pages on the site. there are two new kinds of pages that can be created: the landing page and the content page. landing pages are ones like `/people` and `/research` that have a big image across the top and a tagline. content pages are basically other "regular" pages that just have text on them - like the about page (`/about`).

content pages:
1. log into the new admin interface (`/cms`)
2. play around with the "pages" tree on the left. if you click the folder icon, you see what pages are listed under that page. if you click the pencil, you edit that page. if you click the arrow, you go down one level in the tree.
3. try creating a new content page. you can create one underneath the homepage, or underneath any of the existing landing pages. you could try a variety of different formatting options for the body text.
4. visit your new content page using its `/pages` url. does everything look right? 

landing pages:
1. repeat steps 1 and 2 above
2. try creating a new landing page. the **only** place you should be allowed to do this is underneath the homepage.
3. visit your new landing page using its `/pages` url. does everything look right? check the header image and tagline, if you set them.

# dev notes
this is a new app that will be created to house page-related parts of resources. eventually it may be fully generalized and so will just be installed and used as-is in other projects.

## new models
- [x] `ContentPage` (port from s&co)
- [x] `LandingPage` (port of `ContentLandingPage` from s&co)
- [x] `HomePage` (port s&co `HomePage` and add logic from cdh-web view)
- [x] `PagePreviewDescriptionMixin` (port from s&co)

## templates
- [x] update homepage template
- [x] update landing page template
- [x] update content page template
## hooks
- [x] port blockquote feature from s&co
## tests
- [x] test models
- [x] convert homepage template tests to wagtail model tests
- [x] convert landingpage template tests to wagtail model tests
- [x] contentpage template tests?

**Comment by rlskoeser** [comment]
We should consider adapting work from ppa — https://github.com/Princeton-CDH/ppa-django/blob/develop/ppa/pages/models.py
at least the expanded list of html tags for paragraphs, and we probably want to add embed blocks

**Comment by cvansant** [comment]
For the normal page:

@thatbudakguy I wasn't able to embed videos using the plus sign + "embed". It says "cannot find an embed for this url." I tried the links on [Media Central.](https://mediacentral.princeton.edu/media/Center+for+Digital+Humanities+Overview/0_mnz807tm/192064963)

**oembed**: https://mediacentral.princeton.edu/id/0_mnz807tm?width=608&height=402&playerId=25624581
**embed**: <iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1449362/sp/144936200/embedIframeJs/uiconf_id/25624581/partner_id/1449362?iframeembed=true&playerId=kaltura_player&entry_id=0_mnz807tm&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_3tdju5t2" width="400" height="285" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe> 

In addition, I tried adding a photo. Though I was able to do it, the photo was distorted: https://cdh-test-web.princeton.edu/pages/engage/graduate-students/new-grad-program/

Otherwise it worked well!

**Comment by cvansant** [comment]
@thatbudakguy 

For the landing page, I had the same issues as above with the photo distortion and the videos not working.

Two more things: 1) please move the “header image” field up above the text editor part. It's hard to figure out where to add that big image for landing pages. 2) And the ability to have captions for photos.

Here's the page I made: https://cdh-test-web.princeton.edu/pages/new-heading/

**Comment by thatbudakguy** [comment]
@cvansant OK, this is ready for another look.

- video embeds: I steered you wrong here, sorry about that. Wagtail works via oEmbed, but it doesn't actually accept regular oEmbed links - it wants you to paste the URL from the thing you're trying to embed, so that it can "magically" get the right oEmbed link from that. However, this functionality only works for some popular sites (like YouTube), and not for e.g. Princeton's media central. We could make it work, but probably won't (yet) as part of this update. so go ahead and try by just pasting in any regular old YouTube URL to make sure that works.
- I added the captioned image and SVG image options from s&co; they should work exactly the same. fortunately you already know how they work and are well-equipped to test them!
- I wasn't able to see your example pages because the test data got reset, but when I tested using the captioned image, the styles looked right (no warping). see if that's resolved for you too.
- I reordered the landing page fields to put the header image above the body text.

**Comment by cvansant** [comment]
@thatbudakguy The video is in a long, thin box: https://cdh-test-web.princeton.edu/pages/engage/grants/external-funding-opportunities/

**Comment by cvansant** [comment]
@thatbudakguy I have no meaningful idea what an svg image is, alas, but I have one on my laptop (an S&Co logo) and tested it and it worked! Images look good with or without captions. Only thing is if you try to italicize a caption, it doesn't work because it's already in italics. But whatever. 

Landing page is much clearer now!

**Comment by cvansant** [comment]
Shouldn't have closed it yet because of the video situation!

**Comment by thatbudakguy** [comment]
@cvansant added some basic styles for embeds to make them not as flat.

**Comment by cvansant** [comment]
@thatbudakguy Looks good with YouTube! Closing the issue.
