### ISSUE TITLE
As an admin, I want an import of content from the previous version of the site so that all the information available on the old site is migrated to the new version.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#2]
## Notes for testing
Updates 9/22:
- now displaying tagline/subtitle on project detail page
- confirmed drag and drop order works the way I think, updated import script to flip order 
-  tweaked styles for profile education section
Updates 9/21 for second round of testing.
- Ran a complete import on fresh data from production this morning 9/21, so content should match what is there today.
- See comment for notes on changes made in response to first round testing feedback: https://github.com/Princeton-CDH/cdh-web/issues/2#issuecomment-330964237
- Be aware of manual cleanup that needs to be done after import (including updating the menus) #41 I have left things largely as is after the import so you can test the clean up as well, with the following exception: I associated images for one event and two projects and marked those projects as highlighted to test image and homepage display.

import content:
- [x] people
- [x] events
- [x] projects
- [x] blog posts
- [x] content pages
- [x] display tagline on project detail page
- [x] check drag & drop sort order
- [x] check formatting on profile page education

**Comment by rgmunson** [comment]
**People**: 
- Staff members on the old site all appear on the new site. 
- The landing page for staff is ordering alphabetically by name rather than by role because the import assigned the roles all the same level; sort order for staff roles for staff will need to be manually assigned. 
- Assigned a few test numbers for sort order it reorders the page from smallest number to highest number (I had  counterintuitively assigned the most important roles higher values but we can change that) and it works.
- Redirect from old staff landing page and members' pages to new ones not currently functional. 
- Text from member pages has imported but the styles have not (e.g. no italics or underlining for titles in CVs).

**Comment by rgmunson** [comment]
**Events**

- All the events from the old site successfully imported to the landing page of the new site.
- In example of lecture on 9/20 all text from old site transferred *Except* for photo credit, which must be in another field?
- Reading Group info from the old site is not on the new site, most likely because Jim entered the event details sometime after 9/12 when the initial import was run. Re-run script to see if that's the problem.
- All events that have content on the old site have content on the new site except for the reading group (suggests it will be fixed by rerunning import script). Placeholder events on the old site have the same amount of info, or lack thereof, as on new site.

**Comment by rgmunson** [comment]
**Projects**

- Cards for projects display correctly on landing page (although without images, which we'll add manually).
- Titles have imported correctly. Subtitles (a field that exists only on the old site) imported to field for "short description." Field for "project summary" (on old site) has imported to "long description" on new site; "long description" is now lost. Best test case for this might be MEP since it has a title, subtitle, short description, and long description. New admin only has 3 fields where old admin had 4 - what to do with subtitle?
- Although it's clear that the project members were imported into the admin interface they aren't displaying on the site itself. It's not even that none of them are displaying on the site but they display inconsistently, e.g. Mary is the only name for MEP, PPA has Jean and Meredith but not Meagan or Collette. In all cases the admin on the site shows all the names. 
- The link redirects are working.

**Comment by rgmunson** [comment]
**Blog posts**

- No blog posts that went up on the old site after 9/12 are on the new site but this should be taken care of by rerunning the import script.
- The titles and contents have imported correctly but none of the tags have. (These may need to be done manually like the authors?) From a user perspective having tags to browse with (and "previous" and "next" buttons) would be nice--I'll try to capture in a user story. 
- Redirects for links are not working.

**Comment by rlskoeser** [comment]
Made some updates based on testing feedback.

## people
- added redirects from old staff and profile pages to new
- was not able to find any instances where formatting didn't come through the import

## events
I couldn't find any content that didn't import, so I think the discrepancy must be due to edits made after the export I was working from.  We'll check again with a fresh import.

## projects 
Revised mapping as follows:
- old project subtitle -> new short description
- old project description -> new long description
- old project summary -> description in metadata with generate desc set to false
I've added logic to the display page to display summary or short description as the content excerpt (we can test that separately if it's helpful).
I haven't addressed member display but I think that's an issue with the project page and not the import.  (It only displays current members so would display nothing if grant is past.)  I'm reopening #21 for that.

## blog posts
- Fixed the logic to import keywords properly.  Thanks for catching this! I misunderstood how they worked!
- Categories are not preserved in the import, will (eventually) be replaced by tags.
- Added logic to redirect from old urls to new.  Currently only main blog list and individual blog pages are supported (archive pages still todo).

**Comment by jabauer** [comment]
**People**
Redirects work from old site URLs
Only formatting issue (which might be a design issue): The short lenght of the info column, means that Degree lines tend to wrap and make it harder to read.

**Comment by jabauer** [comment]
**Events**
All content appears to have imported correctly.  Including new content in the new import.

**Comment by jabauer** [comment]
**Projects**
- Subtitles do not appear on the Project Page, only on the project card.  May need to add a specific SUBTITLE field in the Project model (see bitKlavier as an example)
- all other content imports over
- ranking has been reversed in this system, so the PI is last and the consultants are first.  Up to @rlskoeser to decide whether it's easier to flip the ranking algorithm so it counts up, or go in manually and reverse all the rankings.

**Comment by jabauer** [comment]
**Blog**
- urls redirect from old site to new
- Keywords appear at bottom of posts, but are not links
- Categories are gone, which is fine
- When the blog archive is broken down by year, the months are not links, just text
