### ISSUE TITLE
As a user, I want to view sponsored project details so I can read about project goals, progress, and contributors.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#21]
## Notes for testing
Updated 9/21 to improve project member handling.  Now displays project members associated with the most recent grant, even if the grant period has ended.  Now also displays project alumni (project members not associated with the most recent grant.) Also better handling for person name display.

---
- [x] display current members _or_ members of last active grant if no current grant
- [x] automatically display project alumni? (if easy)

**Comment by mnaydan** [comment]
Am able to view individual project page, project website link, project description content, and contributors. Multiple members with the same role display in a column underneath the role heading. Roles and their related members display according to sort order.

**Comment by rlskoeser** [comment]
Reopening because it's not handling imported project members correctly.  I think it only displays _current_ project members; should probably modify to display people associated with the last active grant if there is no current one?

**Comment by rlskoeser** [comment]
Perhaps we can also display project alumni programmatically rather than manually adding them.

**Comment by rgmunson** [comment]
Further comments on the project members: the import displays members alphabetically by role on the project pages rather than having the PI at the top etc. It doesn't seem like there's a way to change this in the admin by drag-and-drop so we'll need to manually assign roles the numerical value we'd like them to have. Otherwise all project details are displaying correctly (with the exception of the the fact that the subtitles don't seem to have imported as noted on issue #2).
