### ISSUE TITLE
project admin edit pages load slowly, especially for large projects

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#212]
## testing notes
Membership has been removed from the project edit page in order to expedite editing for large projects with many members.

Check that the project edit page is more responsive now, and check that you can add and edit memberships separately.

**Comment by rlskoeser** [comment]
This is most evident on S&co, since it has such a large number of grants and team members.

Simplest solution: remove membership inline from main project edit page and edit them directly, not as inlines. 

Next simplest: implement simplest solution + also remove `project` foreignkey from `Membership` model. (It's redundant since projects are currently associated with membership through grants as well as directly). Not sure what the implications are for the code, but expect it wouldn't be too hard to make this refactor (maybe a `project` property to stand in for the removed foreign key).

Complicated solution: revise memberships so they attach to the project directly with start and end dates instead of being linked to specific grants.  This solution is probably out of scope for now, but we might want to create an issue (if we don't already have one?) to track this change to the data model so we can document it. (I know we've discussed it in the past; after thinking about it more I think it would solve a few different problems.)

@thatbudakguy I revised to specify that I was talking about the project admin edit page (in case it was unclear), and relabeled as a bug. Do you agree?

**Comment by cvansant** [comment]
Looks good
