### ISSUE TITLE
As a user, I want to view event details so I can decide if I'm interested and know when and where to attend.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#25]
## Notes for testing
Update 9/21: I think the image display issue was a media/deploy problem that's been resolved, please retest.

**Comment by kateclairmont** [comment]
Event details such as where and when to attend are displaying. However, for the event "Intro to DH," and a couple others, the descriptions and pictures are not appearing.

**Comment by rgmunson** [comment]
The only event with an associated image is the Open House, presumably because we are going to need to upload images manually since they were not part of the import. Descriptions are displaying where there are descriptions on the original site (and not when they are not). Time and location info all still displaying properly.
