### ISSUE TITLE
As a content editor, I want existing people migrated to wagtail so that I can manage them in the new system.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#253]
# testing notes
this one is pretty straightforward to test - we just want to make sure that everyone who has a visible profile on the CDH site still has one, and that it looks more more less the same. you can try it out by finding the URLs of current profiles like https://cdh.princeton.edu/people/camey-vansant/, and then comparing the new version (https://cdh-test-web.princeton.edu/pages/people/camey-vansant/). probably a good idea to try at least one of current/past staff, students, faculty, etc.

everything should look the same _except_ for attachments (if people had a pdf of a resume, for example), which will look weird until we finish #246, so ignore those.

note that how people appear on the list pages (like `/people/staff`) isn't covered by this issue.

# dev notes
depends on #186

**Comment by cvansant** [comment]
The menu items that are on the left of some staff pages (e.g. Twitter, ORCID, website) are in a different order on the test site than on the current live site. Here is the [current MM page](https://cdh.princeton.edu/people/meredith-martin/) and the [test site MM page](https://cdh-test-web.princeton.edu/pages/people/meredith-martin/).

I notice two differences between the two Kate Carpenter pages. Here's the [current site](https://cdh.princeton.edu/people/kathryn-carpenter/) and here's the [test site](https://cdh-test-web.princeton.edu/pages/people/kathryn-carpenter/). The photo color looks slightly different. Also, for her blog posts, the test site attributes the posts to "kbc." For Elena Ryan, the profile photos are two different sizes: [current site](https://cdh.princeton.edu/people/elena-m-ryan/) and [test site](https://cdh-test-web.princeton.edu/pages/people/elena-m-ryan/).

Also, I don't know who to test faculty since they just link to outside pages.

**Comment by thatbudakguy** [comment]
Interesting about the link order; I think as part of Kevin's work on #181 we will be able to make the order controllable in the admin so for now the difference doesn't matter.

Re: the Kate image, super weird!! I think this might be related to the fact that some of the images are corrupted and missing EXIF data; that's the only thing I can think of that would cause them to have slight discolorations or changes like that. There's not really anything we can do because the file was modified, but I guess this shows what the result of that is. Ping @rlskoeser if you didn't see it already.

About the blog post author listings, that will be fixed in #185, but good to have a reminder that we'll need to update it here (blog posts aren't yet associated with the new `Person` and are still tied to user accounts, which is why they say `kbc`).

Sorry about mentioning faculty, I can't think of a case where they'd have a profile, so no need to test.

I think this can be closed. @rlskoeser lmk if you agree.

**Comment by rlskoeser** [comment]
@thatbudakguy I agree, this can be closed based on Camey's notes above — we already have plans to handle the problems she identified.

Whatever's going on with the images, I think it makes sense to include investigating that as part of #271 

@cvansant thank you for the great testing!
