### ISSUE TITLE
As a search engine, I want a sitemap of all pages on the CDH site so that I can index them for users to search.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#254]
check for cases where priority is used, e.g. featured blog posts. nice to have.

send the output to a sitemap validator to confirm no errors; maybe ask kevin to test.

**Comment by rlskoeser** [comment]
Sitemap looks pretty good — content looks accurate, and I see the adjustments to priority for featured blog posts (we should probably unfeature some of the older ones...) and projects that are highlighted or built by cdh.  I modified a page and checked that the last modified date updated correctly, and unpublished the change to check that it was removed from the sitemap.

I did notice one small thing — dynamic views like the people and project list pages are no longer included in the sitemap. I checked in production, and they were included there because we had stub mezzanine pages for them, but we don't anymore.  This isn't a deal breaker, since it's a small number of pages, but they are kind of important pages and we should figure out how to address this soon.  One possibility is to create two different sitemaps and use a sitemap index — one sitemap for wagtail pages and one for non-page views with a list of the views/urls that should be included. I think I've implemented something like that before we should be able to borrow from.

**Comment by rlskoeser** [comment]
@thatbudakguy this is sort of what I was thinking of: https://github.com/Princeton-CDH/ppa-django/blob/main/ppa/archive/sitemaps.py#L7-L22

**Comment by thatbudakguy** [comment]
seems reasonable. should we put this on the list for 3.0.1, or try to get it added now?

**Comment by manawinters** [comment]
@thatbudakguy, I'm sorry, but I'm not clear on what I need to test for this issue.

**Comment by thatbudakguy** [comment]
confirmed that dynamic views are now included, and priority calculation/last modification date remain correct.
