### ISSUE TITLE
As a moderator, I want People automatically organized into person list pages so I don't have to manually manage these pages.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#267]
# testing notes
This issue refers to the person list views on the current CDH site - [sponsored projects](https://cdh.princeton.edu/projects/), [staff projects](https://cdh.princeton.edu/projects/staff/), and [working groups](https://cdh.princeton.edu/projects/working-groups/) (we treat working groups as a type of project for simplicity).

## as a user
We want to make sure that the list pages exist on the new site at the same URLs, and that the same people appear on each list. The corresponding URLs on the test site are:

- <https://cdh-test-web.princeton.edu/people/staff/>
- <https://cdh-test-web.princeton.edu/people/students/>
- <https://cdh-test-web.princeton.edu/people/affiliates/>
- <https://cdh-test-web.princeton.edu/people/executive-committee/>

check a few people on each list and confirm that things look the same as they do in production (the real cdh site). there may be small differences in the images displayed on people's "cards"; this is an acceptable difference (unless they look totally horrendous). for people, it's important to also confirm that the right text is shown underneath the person's name, since this **changes based on which list you're looking at**.

the "students" and "affiliates" pages have page intros (the short bits of text at the top of the list); you should see this same text on the test site versions of those pages.

## as a moderator
In the [admin site](https://cdh-test-web.princeton.edu/cms/), expand the main page tree under "home", expand "People", and confirm that link pages have been created for each of the people list pages. If you edit one of these special link pages, you should only see a title and a url for the page within the site. These special pages are used to manage the site's navigation menu; the actual display of people on the list page is handled via code. Try changing the title and see if the name of the page in the site's navigation menu also changes.

also in the admin site, check out the menu on the left called "Snippets". this is new; it's where small pieces of text (like page intros) will be stored and edited. you should be able to find the page intro snippet for the "students" and "affiliates" list pages here; go ahead and edit them and see if your changes are reflected when you visit the page. you might need to refresh multiple times for the changes to take effect.

# dev notes
**see PR #269**

see also (and depends on) #186. The new `PersonIndexPage` will probably be an abstract `Page` which we then subclass to pick a particular queryset/filter and create individual pages like "staff", "students", etc.

- [x] `PersonQuerySet` (old `ProfileQuerySet` - now operates at level of `Person`)
- [x] `PersonListPage` (uses QS methods to replace current person views)
- [x] update views for profile -> person
- [x] update templates for profile -> person
- [x] shift person card logic to views instead of template
- [x] new unit tests for views + new fixtures
- [x] create snippet for page intro text; link to link page from wagtail menus
- [x] update exodus to populate snippets from existing wagtail pages
- [x] render snippet if present

revisions after testing
- [x] fix project director label for student affiliates
- [x] display multiple roles for student affiliates
- [x] check faculty/affiliate link page url 
- [x] check student page thumbnail display and adjust image resizing logic
- [x] see if we can include page intro (if any) modification time in last modified header for person list views
- [x] remove speaker page

**Comment by cvansant** [comment]
@thatbudakguy In production, the students who won dataset curation grants are labeled as "2020-2021 Dataset Curation Grant Recipient." On the test site, they are labeled as "Project Director." An example is Harrissa Lamothe. Moreover, in production, some students have multiple roles listed whereas on the test site they only have one role listed (e.g. Kim Bain).

For the link pages, should the url for "affiliates" still say "faculty"? Or should it say "affiliates" now?

Probably unrelatedly, ,the photos are doing weird things. I think perhaps the thumbnails didn't transfer because on the test site we see zoomed out photos for people who submitted their own photos. You see this a lot on the students page.

As for the snippets, the "students" page text is correct but there is a snippet for "affiliates" that is not displayed on either the text site or in production. Technically speaking, there should be a snippet for speakers but there is not. (By the way, why is the speakers page back? we got rid of that. it is also back in production.)

I successfully added text to the staff page and deleted it. I did have to refresh multiple times for the text to go away after I deleted it.

**Comment by rlskoeser** [comment]
Increased points from 3 to 5 to account for the additional complexity

**Comment by manawinters** [comment]
STAFF: 
- The menu (with websites) to the left of photos is missing in the test site (RM and Grant)
- "Recent Posts" is worded slightly differently (NE and RM) - user names (nataliae and rmunson) are listed in test site, but not in production

STUDENTS:
- No link to Dylan Principi's website (Music dept) in the test site
- Glancing through all the students' photos, they appear different (centering/cropping) in the test vs production site. Also, a few photos in the production site are not on the test site (Jessica Lambert and Keely Toledo, which are recent adds - maybe that's why?)

AFFILIATES:
- The order is different in the production and test site (maybe due to title ranking/sort order)?
- No link to Josh Kotin's website (English Dept) in the test site
- Past affiliates - 3 people in the test site that aren’t in the production site -  Weinryb Grohsgal, Dmitri Tymoczko, Angela Creager (DCG recipients)

EXEC COMM:
- Angela Creager, with the title of “Thomas M,” is incorrectly listed under the EC in the test site
- No one’s photo on the EC page has a link to their personal website in the test site
- Sit with - Wind Cowles photo is missing in the test site, Kathleen Crown, Sami Kahn, Will Noel, and Katherine Stanton’s photos are not cropped properly in the test site
 - Past members - Janet Vertesi’s photo is not cropped properly

I successfully changed the title of "Students" in the navigation menu of the Wagtail admin site. Was it also supposed to update in the test site (because I don't see the change)?

Under Snippets, I was also was able to make edits in Students and see the changes in the test site.

**Comment by rlskoeser** [comment]
Opened a pull request with fixes for some of these. Notes:
- fixed profile page related links
- recent post wording is because the blog hasn't been exodized yet, so that's fine for now
- external links across all pages were not working; my pull request has a fix
- image cropping is different because we're auto-generating the thumbnail from the larger image when there is one, and it was hard to come up with an auto-crop rule that works well fo everything; discussed with @thatbudakguy and we think this is ok for now until have a chance to revisit and refine the image derivative handling. However, I do notice that in some cases the images in QA look worse than they do in my local dev, almost like they aren't honoring the focal point cropping — however, when I look in wagtail admin in qa, the images definitely have focal points detected, and they look correct.
- affiliate sort order was wrong! thanks to Mana for catching that, corrected in my pr
- past affiliates that aren't showing in production: this is because their profiles are _draft_ records in production, and we apparently aren't honoring that. I'm not sure why they are drafts, though! I think they should be listed.
- Angela Creager is in the admin with an EC position but her profile is draft status; we should correct this in the admin site
- new snippet implementation means that the page title can't be changed by wagtail edits (I can't remember if it could before?); I think this is ok, just something to be aware of
- I'm guessing Wind's missing photo is one of the images that isn't being migrated correctly, which we plan to investigate in #271 

@thatbudakguy should we be honoring profile draft/published status? I'm not sure why the some of these are not published in production.

**Comment by rlskoeser** [comment]
@manawinters thanks for the excellent testing notes and for catching so many things.  Two questions specifically for you:
- In the production database, Angela Creager has an Exec Committee position with a start date of 2019-09-08 and no end date. (She isn't listed because her profile page is in draft status.) Was she never on the EC? If so, please remove the EC position in production.
- Weinryb Grohsgal, Dmitri Tymoczko, and Angela Creager aren't listed on the production site affiliates page because their profiles are all in draft status. Do you have any idea why that is?

**Comment by rlskoeser** [comment]
@manawinters notes for re-testing, once the test site has been updated and the exodus script re-run:
- [ ] confirm that links to website/twitter/orcid etc. show up on the left-hand side on staff profile pages
- [ ] confirm that links to external profile pages work for students, faculty, staff
- [ ] confirm that people are sorted by last name on the affiliates page
- [ ] check if image cropping looks better (confirmed with Nick that focal point detection was turned off last time, which is why some of them looked so bad! should be better now) 

I think the other things you've flagged will either be dealt with on other issues (missing images, blog authors showing as usernames) or are limitations of how we've set things up currently (i.e., some page titles won't be editable).

If you want to experiment with the new image focal point detection and cropping, you can find an image in the wagtail admin and edit the focal point box, and then reload the page where that image is used as a thumbnail to see how it resizes it based on the new focal point.

**Comment by thatbudakguy** [comment]
ready to test again!

**Comment by manawinters** [comment]
@rlskoeser, I have confirmed all of the above issues have been addressed/fixed. 

To answer your other questions, Weinryb Grohsgal, Dmitri Tymoczko, and Angela Creager are all Associated Faculty and are on the correct page (Affiliates) with the correct titles, however Angela **also** still appears on the Executive Committee page with the title, "Thomas M." Angela should only appear on the Affiliates page.

**Comment by manawinters** [comment]
@rlskoeser, I used the new image focal point detection and successfully cropped/centered Kathleen Crown.

**Comment by rlskoeser** [comment]
@manawinters thanks for your comments and retesting.

Angela is showing up as exec because there's a position in the database that says she is.  Please remove that in production. I defer to you and @thatbudakguy whether we need to test after that change to confirm it resolves the problem.

I don't know why her title is wrong, but not sure it matters once we fix this. (I think the exec page is the only place it would be displayed).

By way of explanation: the reason there's a difference in production and test is because of how we've changed people and profiles; in the old version, people are listed based on their profile, which can be draft status. But in the new version, profiles are only for people with pages on the site, and people included on lists don't have draft status.

**Comment by thatbudakguy** [comment]
This has been fixed in production and no longer occurs for me with a recent dbdump, so closing.
