### ISSUE TITLE
As a moderator, I want blog posts automatically listed by latest posts, by month, and by year so that I don't have to manually manage these pages.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#287]
# testing notes
(the test banner might get in the way of clicking the "updates" link in the nav menu again - if it does, make sure to click "ok" so that it goes away).

there are a couple unique places to test:
- the main list of all blog posts (https://cdh-test-web.princeton.edu/updates/)
- the list of all blog posts for a particular year, e.g. (https://cdh-test-web.princeton.edu/updates/2020/) for 2020
- the list of all blog posts for a particular month/year, e.g. (https://cdh-test-web.princeton.edu/updates/2020/09/) for sept. 2020

for each of these, we want to check that:
- blog posts that are drafts don't appear
- blog posts are listed in the correct order (by date)
- blog post authors appear correctly

compare with production and see if anything stands out, keeping in mind that there may be recent posts and/or images missing because the data isn't current.

**note** there is one known difference you'll see – blog posts with no author will have nothing listed where an author would be, which is a difference from production (the ones in production use the generic text "CDH staff"). in conversation with @rlskoeser we decided that "CDH staff" wasn't meaningful, so we just allow blog posts to not have an author in 3.0.

# dev notes
borrow tests from events to test the `LastModifiedMixin` views. changes to views should be minimal.
## views
- [x] `BlogYearArchiveView`
- [x] `BlogMonthArchiveView`
- [x] `BlogIndexView`

**Comment by manawinters** [comment]
In the test site: The links on the bottom of the update “[Shakespeare and Company Project Publishes Updated Datasets](https://cdh-test-web.princeton.edu/updates/2021/02/01/shakespeare-and-company-project-publishes-updated-datasets/)” are broken for the “next” blog post (it works for the “previous” blog post, however). The “next” blog post should be “Maps Reveal Intersection of Race and Philly Parish Closures,” but it currently is “CDH Becomes DARIAH’s First U.S. Cooperating Partner” (and when I click on it, I get the chicken).

Otherwise everything else looks good/works!

**Comment by thatbudakguy** [comment]
@manawinters great catch; it wasn't respecting draft status so trying to visit a post that was a draft was leading to the chicken. give it another try; should be fixed now.

**Comment by manawinters** [comment]
@thatbudakguy, when I go to  the Shakespeare and Co Project, it looks like [this](https://cdh-test-web.princeton.edu/updates/2021/02/01/shakespeare-and-company-project-publishes-updated-datasets/).
