### ISSUE TITLE
Design generic search results so that when the user searches generic pages/content they would see a simple list of results 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/cdh-web#364]
Here is the [figma file](https://www.figma.com/file/7P52LnAjsL24HeeJmPChy2/CDH-Web?node-id=0%3A1) for desktop and mobile represented as layout on the page + components with auto layouts implemented

**Comment by thatbudakguy** [comment]
this is great! i think we had talked about having thumbnails for pages that had images, but i'm OK with just using the cdh icons instead — it'll look cleaner and we don't have to deal with the problem of missing images.

my only question is about the pagination: could we see it in different states? I'm wondering if the active page indicator stays in the middle when there are many pages, like PPA's:

<img width="433" alt="Screen Shot 2021-08-05 at 9 59 46 AM" src="https://user-images.githubusercontent.com/4924494/128362879-dcabba24-da50-4afe-b4d1-d0275d8ffe55.png">

or if we just always show all the pages, kind of like how the blog section of the site is currently.

**Comment by gissoo** [comment]
@thatbudakguy Thanks for writing! Re: the pagination – let's make this another issue, was going to ask you how much detail you need about pagination right now, I'll create another issue for that.

**Comment by rlskoeser** [comment]
The search results look good to me too. I presume we can use the existing logic to determine which icon is displayed for a given page? (I think there's a template tag or method that determines it based on url; these are the same icons that are used when pages show up as a tile on their parent page.)

If someone were to link directly to a search, would they be able to see any header branding or navigation, or would they not see any because the search bar is active?

**Comment by thatbudakguy** [comment]
i don't think the current template tag behavior is on @gissoo's radar. my current reading of these designs are that we always use the "page" icon until styles are created for different page types, and that the icon might later indicate the page type (not its position in the hierarchy or URL). but maybe the template tag will ultimately accomplish the same thing...

by way of explanation, the icon logic @rlskoeser mentions is here:
https://github.com/Princeton-CDH/cdh-web/blob/d480de7d412e3d3c508eff6e0726d4ad5a24390f/cdhweb/pages/templatetags/cdh_tags.py#L10-L26

basically, this lets us choose an icon for a page based on the URL to that page. we go down the list above, and if the URL includes one of the words on the left side, we use the icon named on the right side (so anything with `/people/` in the URL uses the "people" or `ppl` icon).

as @rlskoeser mentions, we already use this to pick icons for the tiles at the bottom of pages — you can see here that the contact page URL matches `/contact/` above so it gets the `convo` icon:

<img width="1059" alt="Screen Shot 2021-08-05 at 10 40 35 AM" src="https://user-images.githubusercontent.com/4924494/128369343-062ab4d0-4ee6-4cff-930a-dc9153f48c28.png">

@gissoo what do you think of using this system? I can apply it to the search results so that we can see how it looks.

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser Thank you for writing, as we discussed on Zoom previously, I'm fine with that, love that solution! 

- [Here are the designs for the generic search results](https://www.figma.com/file/7P52LnAjsL24HeeJmPChy2/CDH-Web?node-id=0%3A1) on the "Search Results – Generic Pages" on the Figma file – as we decided we are deprioritizing the pagination, so you don't need to pay attention to the pagination component  – Following the search form component and issue you see the CDH logo at the top of the page (to respond to @rlskoeser 's comment above) 

- I have created the RM and Blue styles here as well – added them to the components – note the components have three properties here (the second two are being used for now till we expand on the search result types): ![Screen Shot 2021-08-16 at 2.24.44 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/598c9c83-5c92-49fa-88af-edec20be05c6)
