### ISSUE TITLE
As a user, I want basic information about the CDH displayed on the homepage so that I can learn about the CDH and read more about its values.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/cdh-web#366]
[Designs on Figma](https://www.figma.com/file/7P52LnAjsL24HeeJmPChy2/?node-id=40%3A181)

# dev notes
This is the implementation issue for #353.

We want a prominently displayed section on the homepage (likely similar to or inspired by #350) that includes a small amount of "about" text and then links to the "about" page so that the user can read more.

- [x] find and add about page/consults page to homepage context for rendering
- [x] render a special featured section on homepage if both these pages exist and are published
- [x] styles for featured section

**Comment by gissoo** [comment]
@thatbudakguy thank you, Nick!! 
- The blue / link underline spacing looks much better now. 
- The consult and the about sections look good on desktop on firefox and chrome, however on mobile on both browsers (testing through the desktop browser responsive feature, not on my phone) there are no margins? In the designs I set it so that the image is not full-width, I don't feel strongly if we want to make it full width, but the body text and the text buttons need a margin of 26px on each side – the section titles and icons also need a margin
![Screen Shot 2021-08-24 at 11 53 15 AM](https://user-images.githubusercontent.com/44615389/130649194-f6147f64-7da0-4c50-8b3c-538199739347.png)
- These also look left-aligned, were they always like this? 
![Screen Shot 2021-08-24 at 11 57 41 AM](https://user-images.githubusercontent.com/44615389/130649854-0b16d655-79b7-4c6b-8886-6da62ca72d1f.png)

- The main nav looks a lot better now with being vertically centered. Except, it looks wrong on my chrome, do you see the below on your chrome as well? If not, it's probably my version then. 
<img width="1585" alt="Screen Shot 2021-08-24 at 11 49 30 AM" src="https://user-images.githubusercontent.com/44615389/130648557-c8b9f7b1-7cd9-4471-bec2-caf72375028d.png">

**Comment by thatbudakguy** [comment]
after coming to grips with reality, i was able to make some changes to the container/padding on both mobile and tablet screens. here's where we're at:

- all content should now have a side margin/gutter, including the new about/consult section on the homepage, even at 320px.
- the left-aligned stuff was indeed always that way (as far as I know), so I left it alone. I agree it would probably look better centered though...maybe we could revisit later. at least with the new margin it's less obvious.
- i couldn't duplicate the main nav thing in chrome...want to try updating chrome, or a hard refresh maybe?

**Comment by gissoo** [comment]
> after coming to grips with reality, i was able to make some changes to the container/padding on both mobile and tablet screens. here's where we're at:
> 
>     * all content should now have a side margin/gutter, including the new about/consult section on the homepage, even at 320px.
> 

- this looks a lot better!! thank you!! But on my desktop browser I still can't get it to show me 320px, it keeps showing me 375px, do you know why? I did a hard refresh as well.

>     * the left-aligned stuff was indeed always that way (as far as I know), so I left it alone. I agree it would probably look better centered though...maybe we could revisit later. at least with the new margin it's less obvious.
> 

- that's ok! Great, we can revisit later, it looks better now! 
>     * i couldn't duplicate the main nav thing in chrome...want to try updating chrome, or a hard refresh maybe?

- I trust you, I have to update mine soon, let's say it's solved.
