### ISSUE TITLE
upgrade django + wagtail

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#413]
- update to newer version of wagtail
- update to newer version of django
- update to newer version of python

### public site
- [x] home page
- [x] blog (list, individual pages, pagination)
- [x] events (list, individual event pages)
- [x] project pages (lists, individual pages)
- [x] people (lists, individual profile pages)
- [x] content pages and landing pages
- [x] search
## editing in wagtail
test editing existing content and adding new:
- [x] content page
- [x] landing page
- [x] blog post
- [x] event 
- [x] project; update grants and members
- [x] profile
- [x] adding new image (upload and associate with something)

**Comment by cvansant** [comment]
PUBLIC SITE

Home page: carousel images are not showing up in Chrome, Firefox, or Safari; i checked to make sure there was a photo selected and that the post was featured but still no photos

Blog posts: alt text showing up where images should be

Events: no images on event card or on actual individual event page

Project Pages: some images show up and some don't (this is true of the thumbnails and of the images on the event page); interestingly, all of the ones that do NOT show up appear to be current projects (for example, Healing, Water & Art, whereas photos are working for past projects. In the cases that photos are not showing up, alt text is shown on the project description page.

People: Older photos show up whereas newer ones don't. On the list, missing images show as blue boxes; on staff profile pages, alt text is shown rather than the image.

Content pages / landing pages: Issue again is images. The landing page for "research" should have an image of PUL but it does not. Images on the other landing pages are fine. Most pages don't have photos but I noticed the Creative Commons license on the project charters page was alt text.

**Comment by cvansant** [comment]
PUBLIC SITE:

Events were in a slightly different order. On the test site, the African Language Tech postdoc deadline came before the MARBAS one. On our current site, it's the opposite. Note the deadline is the same for both of them. Otherwise fine.

**Comment by cvansant** [comment]
Okay, I think it's good! Occasionally a little trial and error was involved (as it is on the actual site) but I got everything to work. I tried out photos, links, PDFs, etc.

**Comment by rlskoeser** [comment]
testing completed successfully! 🎉
