### ISSUE TITLE
people with multiple positions are listed multiple times on the staff page

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#66]

**Comment by rgmunson** [comment]
The bug here appears to be fixed. On the test site, Natasha has 3 positions associated with her name (which you can see in admin) but the staff page only displays her profile with the current position. I added an additional position for Natasha on the production site and similarly only the profile associated with her current position appears on the staff page.

**Comment by rgmunson** [comment]
I ran into this same issue on the production site with my current/former positions producing multiple profiles. I tried to test it on the test site but ran into trouble with the staff page really not loading like it was meant to (images seem to be the problem) and since I don't have time to test more now I'm reopening the issue here.

**Comment by QuakerMom** [comment]
Added second position for RM, saw duplicate list in old version of code, fixed in latest version.
